*** Settings ***
Variables        ../python/variables.py


*** Variables ***
${SCREENSHOT_PATH}    bulk-upload-screenshot
${LOGIN URL}      ${zycus_login_url}
${BROWSER}        Chrome
${USER1}          ${user1_email}
${USER1 PASS}     ${user1_password}
${USER2}          ${user2_email}
${USER2 PASS}     ${user2_password}
${USER3}          ${user3_email}
${USER3 PASS}     ${user3_password}
${FILENAME}       Historical Bulk Upload Template_143_AppX